"""initial_schema

Revision ID: 73fd23df4d64
Revises: 
Create Date: 2026-05-28 00:52:44.625981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73fd23df4d64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('monthly_request_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_token_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_budget_usd', sa.Float(), nullable=False),
    sa.Column('default_model', sa.String(length=50), nullable=False),
    sa.Column('default_language', sa.String(length=10), nullable=False),
    sa.Column('auto_correct', sa.Boolean(), nullable=False),
    sa.Column('show_explanations', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('subscription_id', sa.String(length=255), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('subscription_end_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('key_name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('rate_limit_per_second', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('total_usd', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_usd', sa.Float(), nullable=False),
    sa.Column('discount_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_provider', sa.String(length=50), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('invoice_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_id', sa.String(length=255), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('quotas',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('request_limit', sa.Integer(), nullable=False),
    sa.Column('token_limit', sa.Integer(), nullable=False),
    sa.Column('cost_limit_usd', sa.Float(), nullable=False),
    sa.Column('requests_used', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_used_usd', sa.Float(), nullable=False),
    sa.Column('requests_last_minute', sa.Integer(), nullable=False),
    sa.Column('requests_last_hour', sa.Integer(), nullable=False),
    sa.Column('is_exceeded', sa.Boolean(), nullable=False),
    sa.Column('exceeded_reason', sa.String(length=100), nullable=False),
    sa.Column('minute_window_start', sa.DateTime(), nullable=True),
    sa.Column('hour_window_start', sa.DateTime(), nullable=True),
    sa.Column('exceeded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', 'period_start', name='uq_user_quota_period')
    )
    op.create_index('idx_quotas_user_period', 'quotas', ['user_id', 'period', 'period_start'], unique=False)
    op.create_index(op.f('ix_quotas_user_id'), 'quotas', ['user_id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('input_chars', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('output_chars', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_corrections', sa.Integer(), nullable=False),
    sa.Column('corrections_spelling', sa.Integer(), nullable=False),
    sa.Column('corrections_grammar', sa.Integer(), nullable=False),
    sa.Column('corrections_punctuation', sa.Integer(), nullable=False),
    sa.Column('corrections_style', sa.Integer(), nullable=False),
    sa.Column('queue_wait_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('api_key_id', sa.String(length=16), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_requests_session', 'requests', ['session_id'], unique=False)
    op.create_index('idx_requests_status_created', 'requests', ['status', 'created_at'], unique=False)
    op.create_index('idx_requests_user_created', 'requests', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_requests_api_key_id'), 'requests', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_requests_request_id'), 'requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_requests_session_id'), 'requests', ['session_id'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_requests_user_id'), 'requests', ['user_id'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=16), nullable=False),
    sa.Column('correction_type', sa.String(length=20), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('start_word', sa.Integer(), nullable=False),
    sa.Column('end_word', sa.Integer(), nullable=False),
    sa.Column('before_context', sa.Text(), nullable=False),
    sa.Column('after_context', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('user_ignored', sa.Boolean(), nullable=False),
    sa.Column('is_learned', sa.Boolean(), nullable=False),
    sa.Column('user_accepted', sa.Boolean(), nullable=True),
    sa.Column('user_feedback_at', sa.DateTime(), nullable=True),
    sa.Column('learned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_corrections_confidence', 'corrections', ['confidence'], unique=False)
    op.create_index('idx_corrections_request_type', 'corrections', ['request_id', 'correction_type'], unique=False)
    op.create_index(op.f('ix_corrections_correction_type'), 'corrections', ['correction_type'], unique=False)
    op.create_index(op.f('ix_corrections_request_id'), 'corrections', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corrections_request_id'), table_name='corrections')
    op.drop_index(op.f('ix_corrections_correction_type'), table_name='corrections')
    op.drop_index('idx_corrections_request_type', table_name='corrections')
    op.drop_index('idx_corrections_confidence', table_name='corrections')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_requests_user_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_session_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_request_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_api_key_id'), table_name='requests')
    op.drop_index('idx_requests_user_created', table_name='requests')
    op.drop_index('idx_requests_status_created', table_name='requests')
    op.drop_index('idx_requests_session', table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_quotas_user_id'), table_name='quotas')
    op.drop_index('idx_quotas_user_period', table_name='quotas')
    op.drop_table('quotas')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
